# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dadeb347e41499286fb1cc0b23b0af47512fa478a91b0614602c1d7ac756bfda30f48fa44f789e49e16077f4bc2ff6523c56dfc8186ffeb06abc7204d7231887

test:
  secret_key_base: 65f5903298f6ec21e4450896a2012bb8873ec58693ef5fe6d1d224dee1916c2365a3fecae2dabda264c138cc10b55d5a6d6a1abcda5ab7276016ca8ab03aa7bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
